---
title: "Practica_MD"
author: "Grupo de Prueba"
date: "`r format(Sys.Date(), '%d de %B de %Y')`"
output: bookdown::gitbook
---

# Introducción

Bla Bla Bla

# Objetivos (del negocio)

Bla Bla Bla

# Datos 

Leemos los datos y comprobamos el tamaño de la base de datos.

```{r lectura de datos}
diabetes <- read.csv("~/data/DSLab/Cursos/Data Mining /2018 ERICSSON_SEPT/14. Ejercicios Prácticos/diabetes.csv")
dim(diabetes)
head(diabetes)
summary(diabetes)
```
Podemos observar cómo la variable respuesta *outcome* es continua cuando debería de ser una variable binaria. En el siguiente capítulo realizaremos un análisis exploratorio de los datos que nos servirá para estudiar el comportamiento de las variables y, en caso de ser necesario, transformar dichas variables.

# Preprocesado de datos.

Bla Bla Bla

## EDA. Exploratory Data Analysis.

## Correlación entre las variables.

## Transformación de variables

## Imputacion de datos (datos faltantes)

# Modelado

## k-NN
## Regresión Logística
## Clustering
## Arboles de Decisión
## Bosques Aleatorios
## Support Vector Machines
## Redes Neuronales

# Evaluación

# Visualización y Presentación de Resultados

# Puesta en producción

# Actualización del modelo...
Vuelta a empezar.





